INSERT INTO questions (question_text, answer_text, category, difficulty) VALUES
('If you could have dinner with anyone dead or alive, who and why?', 'Think about: what would you want to learn from them?', 'Hypotheticals', 'easy'),
('What is your favorite childhood memory?', 'Focus on the feeling it gave you.', 'Getting to Know You', 'easy'),
('If you could live anywhere in the world, where would it be?', 'Consider climate, culture, and lifestyle.', 'Hypotheticals', 'easy'),
('What is the most adventurous thing you have ever done?', 'Did it change you?', 'Getting to Know You', 'medium'),
('If you could have any superpower, what would it be?', 'How would you use it?', 'Hypotheticals', 'easy'),
('What is your biggest fear?', 'Is it rational or irrational?', 'Deep Thoughts', 'medium'),
('What is one thing you want to achieve in your lifetime?', 'Is it personal or professional?', 'Deep Thoughts', 'medium'),
('If you won the lottery, what is the first thing you would buy?', 'Would you share it?', 'Hypotheticals', 'easy'),
('What is your favorite book or movie?', 'Why does it resonate with you?', 'Getting to Know You', 'easy'),
('If you could change one thing about the world, what would it be?', 'Think big.', 'Deep Thoughts', 'deep'),
('What are you most grateful for today?', 'It can be something small.', 'Getting to Know You', 'easy'),
('If you could go back in time, what advice would you give your younger self?', 'Be kind to yourself.', 'Deep Thoughts', 'medium'),
('What is your hidden talent?', 'Don''t be shy!', 'Getting to Know You', 'easy'),
('If you could only eat one food for the rest of your life, what would it be?', 'Think about variety and taste.', 'Hypotheticals', 'easy'),
('What is the best gift you have ever received?', 'Was it the item or the thought?', 'Getting to Know You', 'easy'),
('If you could switch lives with someone for a day, who would it be?', 'What would you do?', 'Hypotheticals', 'easy'),
('What is something that always makes you laugh?', 'Share a funny story.', 'Getting to Know You', 'easy'),
('If you were stranded on a desert island, what three items would you bring?', 'Survival or comfort?', 'Hypotheticals', 'easy'),
('What is your dream job?', 'Is it different from what you do now?', 'Getting to Know You', 'medium'),
('What is the most important lesson you have learned in life so far?', 'How did you learn it?', 'Deep Thoughts', 'deep'),
('If you could master any skill instantly, what would it be?', 'How would it change your life?', 'Hypotheticals', 'easy'),
('What is your favorite way to relax?', 'Do you prefer solitude or company?', 'Getting to Know You', 'easy'),
('If you could travel to outer space, would you go?', 'Why or why not?', 'Hypotheticals', 'medium'),
('What is one thing you can''t live without?', 'Is it a person, object, or feeling?', 'Getting to Know You', 'easy'),
('If you wrote a book about your life, what would the title be?', 'Think of a catchy title.', 'Deep Thoughts', 'medium'),
('What is the kindest thing someone has ever done for you?', 'How did it make you feel?', 'Deep Thoughts', 'medium'),
('If you could witness any historical event, what would it be?', 'Would you intervene?', 'Hypotheticals', 'medium'),
('What is your favorite holiday tradition?', 'Who do you share it with?', 'Getting to Know You', 'easy'),
('If you could be an animal, which one would you be?', 'Think about their characteristics.', 'Hypotheticals', 'easy'),
('What is a goal you are currently working towards?', 'What steps are you taking?', 'Getting to Know You', 'medium'),
('If you could eliminate one chore from your life, what would it be?', 'Why do you dislike it?', 'Hypotheticals', 'easy'),
('What is the best piece of advice you have ever been given?', 'Who gave it to you?', 'Deep Thoughts', 'medium'),
('If you could invent something, what would it be?', 'What problem would it solve?', 'Hypotheticals', 'medium'),
('What is your favorite season and why?', 'What do you love about it?', 'Getting to Know You', 'easy'),
('If you could learn any language, what would it be?', 'Where would you use it?', 'Hypotheticals', 'easy'),
('What is something you are proud of?', 'Don''t be humble.', 'Getting to Know You', 'medium'),
('If you could meet your great-grandchildren, what would you say to them?', 'What wisdom would you share?', 'Deep Thoughts', 'deep'),
('What is your favorite family tradition?', 'How did it start?', 'Getting to Know You', 'easy'),
('If you could have a conversation with your future self, what would you ask?', 'Are you happy?', 'Deep Thoughts', 'deep'),
('What is something you have always wanted to try but haven''t yet?', 'What is stopping you?', 'Getting to Know You', 'medium'),
('If you could cure one disease, what would it be?', 'Why is it important to you?', 'Hypotheticals', 'deep'),
('What is the most beautiful place you have ever been?', 'Describe it.', 'Getting to Know You', 'easy'),
('If you could have an unlimited supply of one thing, what would it be?', 'Is it material or immaterial?', 'Hypotheticals', 'easy'),
('What is your definition of success?', 'Has it changed over time?', 'Deep Thoughts', 'deep'),
('If you could relive one day of your life, which one would it be?', 'Why was it special?', 'Deep Thoughts', 'medium'),
('What is something that challenges you?', 'How do you overcome it?', 'Deep Thoughts', 'medium'),
('If you could be famous for one thing, what would it be?', 'Would you enjoy the fame?', 'Hypotheticals', 'medium'),
('What is the most interesting fact you know?', 'Where did you learn it?', 'Getting to Know You', 'easy'),
('If you could change your name, what would you choose?', 'Why that name?', 'Hypotheticals', 'easy'),
('What is one thing you hope to be remembered for?', 'What is your legacy?', 'Deep Thoughts', 'deep');
