-- Table-Talk MVP Seed Data
-- Merged from v1.2 Questions and Legacy Data
-- Total Questions: 461

TRUNCATE TABLE questions RESTART IDENTITY;

-- Open Ended Questions
INSERT INTO questions (question_text, answer_text, question_type, context, difficulty) VALUES
('If you could have dinner with anyone dead or alive, who and why?', '''Think about: what would you want to learn from them?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to spend a weekend?', '''Do you prefer adventure or relaxation?''', '''open-ended''', '''Exploring''', '''easy'''),
('What was the last book or movie that really moved you?', '''Why did it resonate with you?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could travel anywhere tomorrow, where would you go?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What is one hobby you have always wanted to pick up?', '''What has stopped you so far?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your go-to comfort food?', '''Is there a memory attached to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('Who has been the biggest influence on your life?', '''In what way did they shape you?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is the best piece of advice you have ever received?', '''Did you follow it?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could master one skill instantly, what would it be?', '''How would you use it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your earliest childhood memory?', '''How does it make you feel now?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is something that always makes you laugh?', '''Why do you find it funny?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could live in any era, which one would you choose?', '''What appeals to you about that time?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your biggest pet peeve?', '''Why does it bother you?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one thing you are really proud of?', '''What did it take to achieve it?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could trade lives with someone for a day, who would it be?', '''What would you do in their shoes?''', '''open-ended''', '''Exploring''', '''easy'''),
('If we could drop everything and move to another country, where would we go?', '''How would our lives change?''', '''open-ended''', '''Established''', '''medium'''),
('What is one meaningful tradition you want us to start?', '''Why is it important to you?''', '''open-ended''', '''Established''', '''medium'''),
('If money were no object, what would our ideal day look like?', '''What would we do together?''', '''open-ended''', '''Established''', '''medium'''),
('What is one thing you admire most about me?', '''How does it inspire you?''', '''open-ended''', '''Established''', '''medium'''),
('When do you feel most loved by me?', '''What specific actions trigger that feeling?''', '''open-ended''', '''Established''', '''medium'''),
('What is a challenge we have overcome that made us stronger?', '''What did we learn from it?''', '''open-ended''', '''Established''', '''medium'''),
('If you could change one thing about our daily routine, what would it be?', '''How would it improve our lives?''', '''open-ended''', '''Established''', '''medium'''),
('What is your favorite memory of us together?', '''What makes it stand out?''', '''open-ended''', '''Established''', '''medium'''),
('If we started a business together, what would it be?', '''What roles would we each play?''', '''open-ended''', '''Established''', '''medium'''),
('What is one goal you want us to achieve in the next year?', '''How can we support each other?''', '''open-ended''', '''Established''', '''medium'''),
('How have we changed since we first met?', '''Is it for the better?''', '''open-ended''', '''Established''', '''medium'''),
('What is one thing you wish I understood better about you?', '''How can I learn more?''', '''open-ended''', '''Established''', '''medium'''),
('If we could relive one day from our past, which one would it be?', '''Would you change anything?''', '''open-ended''', '''Established''', '''medium'''),
('What is the most romantic thing I have ever done for you?', '''Why did it mean so much?''', '''open-ended''', '''Established''', '''medium'''),
('How do you see our future together in 10 years?', '''What are you most excited about?''', '''open-ended''', '''Established''', '''medium'''),
('What does a "meaningful life" mean to you now compared to 20 years ago?', '''How have your priorities shifted?''', '''open-ended''', '''Mature''', '''deep'''),
('What is the most valuable lesson our relationship has taught you?', '''How has it changed you as a person?''', '''open-ended''', '''Mature''', '''deep'''),
('If you could give your younger self advice about love, what would it be?', '''Would you have listened?''', '''open-ended''', '''Mature''', '''deep'''),
('What legacy do you want us to leave behind?', '''How do we start building it now?''', '''open-ended''', '''Mature''', '''deep'''),
('What is one thing you have forgiven me for that was hard?', '''How did you find peace with it?''', '''open-ended''', '''Mature''', '''deep'''),
('How has your definition of "happiness" evolved over the years?', '''Are you happier now?''', '''open-ended''', '''Mature''', '''deep'''),
('What is one fear you have about aging?', '''How can we face it together?''', '''open-ended''', '''Mature''', '''deep'''),
('What is the most profound moment of connection we have ever shared?', '''What made it so deep?''', '''open-ended''', '''Mature''', '''deep'''),
('If you could apologize for one thing in our past, what would it be?', '''Why does it still linger?''', '''open-ended''', '''Mature''', '''deep'''),
('What is something you still want to discover about yourself?', '''How can I help you explore it?''', '''open-ended''', '''Mature''', '''deep'''),
('How do you want to be remembered by me?', '''What stories do you hope I tell?''', '''open-ended''', '''Mature''', '''deep'''),
('What has been the greatest test of our commitment?', '''How did we pass it?''', '''open-ended''', '''Mature''', '''deep'''),
('What does "unconditional love" look like in practice for us?', '''Do we achieve it?''', '''open-ended''', '''Mature''', '''deep'''),
('If this was our last conversation, what would you want me to know?', '''What is left unsaid?''', '''open-ended''', '''Mature''', '''deep'''),
('What is the spiritual or philosophical core of our union?', '''What binds us beyond the physical?''', '''open-ended''', '''Mature''', '''deep'''),
('If you could solve one world problem, what would it be?', '''Why is this one most urgent?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is a small act of kindness you will never forget?', '''Who showed it to you?''', '''open-ended''', '''Exploring''', '''medium'''),
('If you could write a book, what would it be about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What is the most beautiful place you have ever seen?', '''Describe it.''', '''open-ended''', '''Exploring''', '''medium'''),
('What is a song that always makes you emotional?', '''What memory is it tied to?''', '''open-ended''', '''Exploring''', '''medium'''),
('What''s a skill you''ve always wanted to learn but never started?', '''Think about: What''''s stopped you?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could travel anywhere tomorrow, where would you go and what would you do first?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your go-to comfort food and what memory does it bring back?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a small thing that happened recently that made you smile?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''re surprisingly good at that most people wouldn''t guess?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could instantly master any musical instrument, which would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to spend a rainy Saturday?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best concert or live performance you''ve ever been to?', '''Consider: What made it special? Who were you with?''', '''open-ended''', '''Exploring''', '''easy'''),
('What''s a hobby you had as a kid that you''d love to pick up again?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any animal as a perfectly trained pet, what would you choose?', '''Think about: How would your daily life change? What adventures would you have together?''', '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite season and why?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a movie you can watch over and over without getting tired of it?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could live in any time period for a year, when would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your ideal Saturday morning like?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a talent you wish you had?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most interesting place you''ve ever visited?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have dinner with any fictional character, who would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite childhood memory?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a food you hated as a child but love now?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to unwind after a long day?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could learn the answer to one question about your future, what would you ask?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a book that had a big impact on you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite thing about where you grew up?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could be fluent in any language instantly, which would you choose?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something simple that brings you joy?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Coffee or tea, and how do you take it?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Mountains or beach for a vacation?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Would you rather explore a new city or relax in nature?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your preferred way to spend free time: active or relaxing?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Early bird or night owl?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer cooking at home or trying new restaurants?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your ideal weather?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('Would you rather read the book or watch the movie?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer planning ahead or being spontaneous?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite type of music to listen to?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer small gatherings or big parties?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your go-to type of exercise or movement?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer texting or phone calls?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite holiday and why?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer sweet or savory snacks?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite time of day?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer solo activities or group activities?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your preferred way to celebrate a birthday?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer summer or winter activities?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite type of cuisine?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer staying in or going out on weekends?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to travel: road trip, train, or plane?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer dogs or cats, and why?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite drink to order at a coffee shop?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer sunrise or sunset?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any superpower for a day, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the weirdest food combination you actually enjoy?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could switch lives with anyone for a day, who would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your guilty pleasure TV show or music?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you won the lottery tomorrow, what''s the first thing you''d buy?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most adventurous thing you''ve ever eaten?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could be famous for something, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your karaoke song?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could invent a holiday, what would it celebrate?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the strangest talent or party trick you have?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could live in any fictional world, where would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your signature dish to cook or order?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could rename yourself, what would you choose?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most random fact you know?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could be on any reality TV show, which one?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your spirit animal and why?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could teleport anywhere right now, where would you go?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best costume you''ve ever worn?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could bring back any fashion trend, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your go-to dance move?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any job for just one week, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the funniest thing that happened to you recently?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could design your dream treehouse, what would be in it?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite joke or pun?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have an unlimited supply of one thing, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most spontaneous thing you''ve ever done?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a moment when you felt completely alive?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Tell me about a time you laughed until you cried.', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the kindest thing a stranger has done for you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite family tradition?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a challenge you overcame that you''re proud of?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best advice you''ve ever received?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a moment that changed your perspective on something?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best gift you''ve ever received?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a skill you learned that surprised you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your proudest accomplishment so far?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a tradition you''d like to start?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best meal you''ve ever had?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a risk you''re glad you took?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you did that scared you at first?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way you''ve celebrated something special?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a lesson you learned the hard way?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most beautiful place you''ve ever seen?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a compliment you received that really stuck with you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''ve done that you never thought you would?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to treat yourself?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a moment when you felt truly grateful?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best surprise you''ve ever received?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a memory that always makes you smile?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''ve created that you''re proud of?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''ve changed your mind about in the last year?', '''Consider: What caused the shift? How did you feel about changing your perspective?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does a perfect day look like for you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a piece of advice you received that actually changed how you live?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What quality do you value most in other people?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you think everyone should experience at least once?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you define success for yourself?', '''Consider: Is it about career', 'relationships', 'personal growth', 'impact?'''),
('What''s a belief you hold that might be unpopular?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does "home" mean to you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s more important to you: stability or adventure?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a cause you care deeply about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does friendship mean to you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re working on improving about yourself?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does creativity play in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your relationship with money like?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you typically handle stress or difficult emotions?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re currently curious about or trying to figure out?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does balance look like in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a value your family instilled in you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you recharge when life gets overwhelming?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your approach to making big decisions?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does spirituality or faith play in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re passionate about that surprises people?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you show care for the people you love?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your relationship with social media?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does self-care look like for you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a habit you''re proud of building?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you handle change in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you wish more people understood about you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your love language?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you define a life well-lived?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve learned about yourself recently?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does humor play in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you approach conflict in relationships?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a boundary you''ve set that you''re proud of?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does authenticity mean to you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you celebrate your wins, big or small?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re learning to let go of?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does nature play in your wellbeing?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you want to be remembered?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a value you refuse to compromise on?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could relive one day from your past exactly as it was, which day would you choose?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s on your bucket list?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('Where do you see yourself in five years?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a dream you had as a child that you still think about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could master any skill overnight, what would it be and why?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you want to accomplish in the next year?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If money and time weren''t factors, what would you spend your days doing?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a place you dream of living someday?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What legacy do you want to leave?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a goal you''re currently working toward?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could start a business tomorrow, what would it be?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s an experience you''ve always wanted to have?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What would your ideal career look like?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a skill you''re currently learning or want to learn?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you want to be brave enough to try?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What kind of impact do you want to have on the world?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a relationship goal you have?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could go back to school, what would you study?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s an adventure you want to go on?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does your dream home look like?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a fear you want to overcome?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could dedicate a year to learning anything, what would it be?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you want your future self to thank you for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What kind of person do you aspire to be?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a creative project you''ve always wanted to start?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could change one thing about your daily routine, what would it be?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a country you dream of exploring?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What would you do if you knew you couldn''t fail?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you want to create or build?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a personal record you want to achieve?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could speak at a TED talk, what topic would you choose?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s an old dream you''d like to revive?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does retirement look like in your ideal world?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you want to be known for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a lesson you learned from a difficult experience?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re still learning to accept about yourself?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a mistake you made that taught you something valuable?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How have you changed in the last five years?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you wish you could tell your younger self?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a strength you''ve discovered about yourself?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re grateful for today?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a fear you''ve overcome, and what helped you through it?', '''Think about: What made the difference? How did you feel after?''', '''open-ended''', '''Exploring''', '''medium'''),
('What''s something difficult you''re currently navigating?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a pattern in your life you''re trying to change?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s the hardest decision you''ve ever had to make?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve forgiven yourself for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does vulnerability play in your relationships?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a time you surprised yourself with your own resilience?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve had to unlearn?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a quality you admire in others that you want to develop?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you practice self-compassion?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you need to hear right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a turning point in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve sacrificed that was worth it?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What motivates you to keep going when things are hard?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a judgment you''ve let go of?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s the best thing about getting older?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re proud of that others might not know about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you define personal growth?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a comfort zone you''ve stepped out of?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve learned about love?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does healing look like for you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a version of yourself you''ve outgrown?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What gives your life meaning?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re learning to be patient with?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a relationship that shaped who you are?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you wish you had more courage to do?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you want to grow in the next year?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a moment when you felt truly seen by someone?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re still figuring out about yourself?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What helps you feel grounded?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a way you''ve become more like yourself over time?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re learning to trust?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What would you do differently if you could start over?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What are you reading, watching, or listening to right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a podcast or show you''d recommend?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something new you''ve discovered recently that excites you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your current favorite restaurant or cafe?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a topic you could talk about for hours?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite way to be creative?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a rabbit hole you''ve fallen down lately?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your go-to activity when you have free time?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''ve been meaning to try?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite playlist or type of music right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a hobby you wish you had more time for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s the last thing that made you laugh really hard?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite local spot?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you collect or enjoy gathering?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a skill you''re currently practicing?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite thing to cook or bake?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a documentary or movie that changed your perspective?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite way to spend a Sunday?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re obsessed with right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite form of exercise or movement?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a game you love to play?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite way to explore a new place?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your go-to comfort food?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''re surprisingly good at?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to spend a rainy day?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could master any musical instrument, which one?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best concert you''ve ever been to?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a hobby from childhood you''d like to revisit?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your ideal Saturday morning?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a movie you can watch over and over?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could live in any time period, when?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to unwind?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Mountains or beach?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer cooking at home or dining out?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite type of music?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Small gatherings or big parties?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Sweet or savory snacks?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite holiday?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Summer or winter activities?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Dogs or cats?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you had a superpower for a day, what would it be?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your guilty pleasure TV show?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most adventurous food you''ve eaten?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the strangest talent you have?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could be famous for something, what?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your spirit animal?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most spontaneous thing you''ve done?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the kindest thing a stranger did for you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your proudest accomplishment?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a compliment that stuck with you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Which superpower would you choose?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('What''s your preferred vacation style?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('How do you prefer to spend free time?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('Pick your perfect meal time:', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('What type of learner are you?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('Your ideal Friday night:', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('How do you recharge?', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('Pick your dream pet:', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('Your go-to exercise:', NULL, '''multiple-choice''', '''Exploring''', '''easy'''),
('If you could live anywhere:', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a book that impacted you?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you won the lottery, first purchase?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your signature dish?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a moment you felt completely alive?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite drink to order?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Sunrise or sunset?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s a food you hated as a kid but love now?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the weirdest food combo you enjoy?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could switch lives with anyone for a day?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best costume you''ve worn?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could live in any fictional world?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the funniest thing that happened recently?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most beautiful place you''ve seen?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have dinner with any fictional character?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way to celebrate a birthday?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your preferred way to travel?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer planning ahead or spontaneity?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the most interesting place you''ve visited?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could be fluent in any language instantly?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any job for one week?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s the best advice you''ve received?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s your favorite way you''ve celebrated something?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could teleport anywhere right now?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have unlimited supply of one thing?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Read the book or watch the movie?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Texting or phone calls?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What''s something you''ve changed your mind about recently?', '''Consider: What caused the shift?''', '''open-ended''', '''Exploring''', '''medium'''),
('What quality do you value most in others?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you define success?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s more important: stability or adventure?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re working on improving?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you typically handle stress?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re curious about right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you recharge when overwhelmed?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your approach to big decisions?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you show care for people you love?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you handle change?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a dream from childhood you still think about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If money weren''t a factor, what would you do?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a goal you''re working toward?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What impact do you want to have on the world?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What do you want your future self to thank you for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a lesson from a difficult experience?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What would you tell your younger self?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a fear you''ve overcome?', '''Think about: What made the difference?''', '''open-ended''', '''Exploring''', '''medium'''),
('What''s a pattern you''re trying to change?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s the hardest decision you''ve made?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('When did you surprise yourself with your resilience?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What motivates you when things are hard?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What are you reading or watching right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does spirituality play in your life?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you celebrate your wins?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a value you won''t compromise on?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you approach conflict?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your relationship with money?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could relive one day from your past?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could master any skill overnight?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could start a business, what would it be?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s an experience you''ve always wanted?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could write a book, what about?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a creative project you''ve wanted to start?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could speak at a TED talk, what topic?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What does retirement look like ideally?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a mistake that taught you something?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re still learning to accept?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What role does vulnerability play in relationships?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a quality you admire that you want to develop?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re proud of that others don''t know?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you wish you had more courage for?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('When did you feel truly seen by someone?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re still figuring out?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a way you''ve become more yourself over time?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What would you do differently if starting over?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s the last thing that made you laugh hard?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you collect?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a documentary that changed your perspective?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite form of movement?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite way to explore new places?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s an artist or band you''re loving right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s a piece of advice that changed how you live?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something everyone should experience once?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re currently learning?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could dedicate a year to learning anything?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something new that excites you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your current favorite restaurant?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s your favorite playlist right now?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('If you could change one thing about your routine?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something you''re working on achieving this year?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What''s something difficult you''re navigating?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What do you think is your purpose in life right now?', '''Reflect on: This can change over time.''', '''open-ended''', '''Exploring''', '''deep'''),
('If you could solve one world problem, which one?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s something you believe that most disagree with?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What does it mean to live a good life?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s your relationship with mortality?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What would you do if today was your last day?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s the most important lesson life has taught you?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What do you think happens after we die?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s something you''re afraid to admit to yourself?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What does unconditional love mean to you?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s a truth about yourself you''ve recently accepted?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What do you think is the meaning of life?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What would you die for?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s your greatest fear?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What do you think is the root of most human suffering?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s something you''ve lost that shaped you?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What does freedom mean to you?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s a question you''re wrestling with right now?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What do you think your purpose on earth is?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s something you know to be true but struggle to accept?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What would perfect happiness look like?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s the bravest thing you''ve ever done?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What do you think is your biggest blind spot?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s a hard truth you''ve had to face?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What legacy do you hope to leave behind?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s something you''d change about society?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s a skill you''ve always wanted to learn?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('Mountains or beach for vacation?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any superpower?', NULL, '''open-ended''', '''Exploring''', '''easy'''),
('What does success mean to you?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('How do you handle stress?', NULL, '''open-ended''', '''Exploring''', '''medium'''),
('What do you think is your purpose in life?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What gives life meaning to you?', NULL, '''open-ended''', '''Exploring''', '''deep'''),
('What''s your favorite memory of us from the past month?', NULL, '''open-ended''', '''Established''', '''easy'''),
('What''s one thing I do that always makes you laugh?', NULL, '''open-ended''', '''Established''', '''easy'''),
('If we could plan a spontaneous weekend getaway, where?', NULL, '''open-ended''', '''Established''', '''easy'''),
('What''s something we''ve never done together that you''d like to try?', NULL, '''open-ended''', '''Established''', '''easy'''),
('What''s your favorite thing about our routine together?', NULL, '''open-ended''', '''Established''', '''easy'''),
('What''s something you need more of from me right now?', NULL, '''open-ended''', '''Established''', '''medium'''),
('How do you think we balance each other out?', NULL, '''open-ended''', '''Established''', '''medium'''),
('What''s a dream you''ve never told me about?', NULL, '''open-ended''', '''Established''', '''medium'''),
('When do you feel most connected to me?', NULL, '''open-ended''', '''Established''', '''medium'''),
('What''s something you appreciate about how we handle disagreements?', NULL, '''open-ended''', '''Established''', '''medium'''),
('How do you want us to grow together in the next year?', NULL, '''open-ended''', '''Established''', '''deep'''),
('What does commitment mean to you?', NULL, '''open-ended''', '''Established''', '''deep'''),
('What''s something you''ve learned about yourself through being with me?', NULL, '''open-ended''', '''Established''', '''deep'''),
('What''s a challenge we''ve overcome that made us stronger?', NULL, '''open-ended''', '''Established''', '''deep'''),
('How can we better support each other''s individual dreams?', NULL, '''open-ended''', '''Established''', '''deep''');

-- Multiple Choice Questions
INSERT INTO questions (question_text, answer_text, question_type, context, difficulty, options) VALUES
