import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import QRScanner from '../components/QRScanner';
import Button from '../components/ui/Button';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Home() {
  const navigate = useNavigate();

  // If there's an error passed in state (e.g. from WelcomeScreen blocked session), show it
  // Wait, navigate state isn't currently used, we're using a raw alert in WelcomeScreen.
  // Actually, alert() blocks the UI thread which is fine for a simple MVP.
  
  const [tableInput, setTableInput] = useState('');
  const [showScanner, setShowScanner] = useState(false);
  const [scanError, setScanError] = useState('');

  const extractTenantQrTarget = (value) => {
    const rawValue = String(value || '').trim();
    if (!rawValue) {
      return null;
    }

    let path = rawValue;
    try {
      if (/^https?:\/\//i.test(rawValue)) {
        path = new URL(rawValue).pathname;
      }
    } catch {
      return null;
    }

    const match = path.match(/^\/r\/([^/]+)\/t\/([^/?#]+)\/?$/i);
    if (!match) {
      return null;
    }

    return {
      restaurantSlug: decodeURIComponent(match[1]),
      tableToken: decodeURIComponent(match[2])
    };
  };

  const handleManualJoin = (e) => {
    e.preventDefault();
    const parsedTarget = extractTenantQrTarget(tableInput);
    if (parsedTarget) {
      setScanError('');
      navigate(`/r/${parsedTarget.restaurantSlug}/t/${parsedTarget.tableToken}`);
      return;
    }

    setScanError('Please enter or scan a tenant QR link in the new format generated by the restaurant dashboard.');
  };

  const handleScanSuccess = (decodedText) => {
    try {
      console.log('[Home] QR Scan Success:', decodedText);
      const parsedTarget = extractTenantQrTarget(decodedText);

      if (parsedTarget) {
        setShowScanner(false);
        setScanError('');
        console.log('[Home] Navigating to:', `/r/${parsedTarget.restaurantSlug}/t/${parsedTarget.tableToken}`);
        navigate(`/r/${parsedTarget.restaurantSlug}/t/${parsedTarget.tableToken}`);
      } else {
        setScanError('This QR code uses an old or invalid format. Please use the new tenant QR code issued by the restaurant.');
      }
    } catch (e) {
      console.error("Invalid QR format", e);
      setScanError('Unable to read this QR code. Please scan a valid tenant QR code.');
    }
  };

  return (
    <div className="min-h-screen bg-[#F3EDE1] text-[#35332E] selection:bg-[#35332E]/10 selection:text-[#35332E] flex flex-col">
      <Navbar />

      <main className="flex-1 pt-32 pb-16 flex flex-col justify-center">
        {/* HERO SECTION - Compact & Centered */}
        <section className="px-6 max-w-4xl mx-auto w-full text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <motion.img
              initial={{ opacity: 0, scale: 0.85, y: -10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              transition={{ duration: 0.7, ease: "easeOut" }}
              src="/catalyst-logo.png"
              alt="Catalyst"
              className="w-28 h-28 md:w-32 md:h-32 mx-auto object-contain drop-shadow-lg mb-6"
            />
            <span className="inline-block px-4 py-1.5 rounded-full bg-[#35332E]/5 text-[#35332E] text-xs font-semibold tracking-wide uppercase mb-8 border border-[#35332E]/10">
              Catalyst
            </span>
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.1] mb-6 text-[#35332E]">
              Connect Deeper <br/>
              <span className="text-[#35332E]">At The Table</span>
            </h1>
            <p className="text-xl text-[#6E6A60] leading-relaxed max-w-xl mx-auto mb-12">
              Scan the QR code at your table to unlock curated conversation starters designed for meaningful connection.
            </p>
          </motion.div>

          <motion.div
            id="scan"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="flex flex-col items-center gap-6 scroll-mt-32"
          >
            <Button
              onClick={() => setShowScanner(true)}
              variant="ink"
              size="xl"
              icon={<span className="text-xl">📷</span>}
              className="shadow-xl shadow-[#35332E]/10 hover:shadow-2xl transition-all px-12 py-5 text-lg"
            >
              Scan QR Code
            </Button>
            {scanError && (
              <div className="max-w-xl rounded-2xl border border-[#35332E]/15 bg-[#35332E]/5 px-4 py-3 text-sm font-medium text-[#35332E]">
                {scanError}
              </div>
            )}
          </motion.div>

          {/* Mini How-It-Works Row */}
          <motion.div
            id="how-it-works"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            className="mt-20 pt-16 border-t border-[#35332E]/10 flex flex-col md:flex-row justify-center items-center md:items-start gap-12 scroll-mt-32 relative"
          >
             <div className="hidden md:block absolute top-[5.5rem] left-[20%] right-[20%] h-0.5 bg-gradient-to-r from-transparent via-[#35332E]/15 to-transparent -z-10"></div>

             {[
               { icon: "📷", title: "Scan", desc: "Use your camera to join instantly" },
               { icon: "🌱", title: "Context", desc: "Choose your relationship vibe" },
               { icon: "💬", title: "Talk", desc: "Answer curated questions together" }
             ].map((step, i) => (
               <motion.div
                 key={i}
                 className="flex flex-col items-center text-center group cursor-default"
                 whileHover={{ y: -5 }}
                 transition={{ type: "spring", stiffness: 300 }}
               >
                 <div className="w-16 h-16 rounded-2xl bg-white/60 border border-[#35332E]/10 shadow-sm group-hover:shadow-md group-hover:border-[#35332E]/20 flex items-center justify-center text-3xl mb-4 transition-all duration-300 relative z-10">
                   {step.icon}
                 </div>
                 <h3 className="font-semibold text-[#35332E] mb-1">{step.title}</h3>
                 <p className="text-xs font-medium text-[#6E6A60] max-w-[120px]">{step.desc}</p>
               </motion.div>
             ))}
          </motion.div>

        </section>
      </main>

      <div id="about">
        <Footer />
      </div>

      {/* Scanner Overlay */}
      {showScanner && (
        <QRScanner
          onScan={handleScanSuccess}
          onClose={() => setShowScanner(false)}
        />
      )}
    </div>
  );
}
