-- ============================================================================
-- Table-Talk - Updated 500 Questions with Tips (400 open-ended, 100 multiple-choice)
-- Context split: Exploring (300) + Established (200)
-- Difficulty split: Exploring (100 easy, 150 medium, 50 deep); Established (50 easy, 100 medium, 50 deep)
-- Tip format stored in answer_text
-- ============================================================================


-- OPEN-ENDED (400)
INSERT INTO questions (question_text, answer_text, question_type, context, difficulty) VALUES
('What is your go-to comfort food?', '''Is there a memory attached to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could travel anywhere tomorrow, where would you go?', '''What would you do first when you arrived?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is a small thing that made you smile recently?', '''Why did it hit you the way it did?''', '''open-ended''', '''Exploring''', '''easy'''),
('What hobby from childhood would you like to pick up again?', '''What would make it fun to restart?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is a movie you can watch over and over?', '''What do you love most about it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite season?', '''What about it fits your personality?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your ideal Saturday morning?', '''What is the first thing you do?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to unwind after a long day?', '''What does it help you reset from?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could instantly master any instrument, what would it be?', '''What would you play first?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one simple thing that brings you joy?', '''How can you get more of it in your week?''', '''open-ended''', '''Exploring''', '''easy'''),
('Coffee or tea, and how do you take it?', '''When did you first get into it?''', '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer planning ahead or being spontaneous?', '''What is a time your style paid off?''', '''open-ended''', '''Exploring''', '''easy'''),
('Do you prefer small gatherings or big parties?', '''What makes a gathering feel comfortable for you?''', '''open-ended''', '''Exploring''', '''easy'''),
('Sunrise or sunset?', '''Where is your favorite place to watch it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite type of music to listen to?', '''What mood do you play it for?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you could have any perfectly trained pet, what would it be?', '''What would your daily life look like with it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is a talent you wish you had?', '''How would you use it if you had it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is the funniest thing that happened to you recently?', '''What made it so funny?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy pizza?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy jollof rice?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy sushi?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy tacos?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy banku?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy pasta?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy waakye?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy fried rice?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy noodles?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is your favorite way to enjoy ice cream?', '''Is there a moment tied to it?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in a beach town, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in a new city, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in the mountains, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in a quiet village, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in a national park, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('If you had a free day in a festival city, what would you do?', '''Who would you want to share it with?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (1)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (2)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (3)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (4)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (5)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (6)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (7)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (8)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (9)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (10)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (11)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (12)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (13)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (14)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (15)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (16)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (17)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (18)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (19)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (20)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (21)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (22)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (23)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (24)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (25)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (26)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (27)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (28)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (29)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (30)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (31)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (32)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (33)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (34)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (35)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (36)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (37)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (38)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (39)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (40)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (41)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (42)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (43)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (44)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (45)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What is one small win you are proud of this week? (46)', '''What did you do to make it happen?''', '''open-ended''', '''Exploring''', '''easy'''),
('What does success mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does happiness mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does friendship mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does home mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does balance mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does growth mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does authenticity mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does freedom mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does purpose mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does self-care mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does discipline mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does joy mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does confidence mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does love mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does trust mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does kindness mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does courage mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does peace mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does impact mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does belonging mean to you?', '''What experience shaped that definition?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (1)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (2)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (3)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (4)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (5)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (6)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (7)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (8)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (9)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (10)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (11)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (12)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (13)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (14)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (15)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (16)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (17)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (18)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (19)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (20)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (21)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (22)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (23)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (24)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (25)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (26)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (27)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (28)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (29)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (30)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (31)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (32)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (33)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (34)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (35)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (36)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (37)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (38)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (39)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (40)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (41)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (42)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (43)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (44)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (45)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (46)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (47)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (48)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (49)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (50)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (51)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (52)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (53)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (54)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (55)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (56)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (57)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (58)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (59)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (60)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (61)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (62)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (63)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (64)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (65)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (66)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (67)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (68)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (69)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (70)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (71)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (72)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (73)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (74)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (75)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (76)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (77)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (78)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (79)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (80)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (81)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (82)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (83)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (84)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (85)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (86)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (87)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (88)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (89)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (90)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (91)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (92)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (93)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (94)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (95)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (96)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (97)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (98)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (99)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What is something you are learning about yourself lately? (100)', '''What triggered that insight?''', '''open-ended''', '''Exploring''', '''medium'''),
('What does forgiveness mean to you, and where is it hardest?', '''What is the line between forgiveness and boundaries for you?''', '''open-ended''', '''Exploring''', '''deep'''),
('What do you think is the root of most human suffering?', '''Where do you see it show up most in daily life?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a truth about yourself you have accepted recently?', '''What helped you accept it?''', '''open-ended''', '''Exploring''', '''deep'''),
('What does a good life look like to you, really?', '''Which part of that is hardest to live out?''', '''open-ended''', '''Exploring''', '''deep'''),
('What would perfect happiness look like for you?', '''What is one obstacle that gets in the way?''', '''open-ended''', '''Exploring''', '''deep'''),
('What does freedom mean to you?', '''What is one choice that would increase your freedom?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (1)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (2)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (3)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (4)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (5)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (6)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (7)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (8)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (9)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (10)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (11)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (12)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (13)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (14)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (15)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (16)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (17)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (18)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (19)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (20)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (21)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (22)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (23)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (24)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (25)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (26)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (27)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (28)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (29)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (30)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (31)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (32)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (33)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a question you are wrestling with right now? (34)', '''What makes it hard to answer?''', '''open-ended''', '''Exploring''', '''deep'''),
('What is a small gesture from me that always lands well?', '''How can I do it more consistently?''', '''open-ended''', '''Established''', '''easy'''),
('What is your favorite photo or memory of us, and why?', '''What was happening in that season?''', '''open-ended''', '''Established''', '''easy'''),
('What is a moment you felt proud of us?', '''What did we do well in that moment?''', '''open-ended''', '''Established''', '''easy'''),
('What is one fun thing we should schedule soon?', '''What is the easiest date and time to make it happen?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (1)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (2)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (3)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (4)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (5)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (6)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (7)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (8)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (9)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (10)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (11)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (12)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (13)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (14)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (15)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (16)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (17)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (18)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (19)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (20)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (21)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (22)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (23)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (24)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (25)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (26)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (27)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (28)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (29)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (30)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (31)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (32)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (33)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (34)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (35)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('What is one small thing we could do today to feel closer? (36)', '''What would make it easy to do?''', '''open-ended''', '''Established''', '''easy'''),
('When do you feel most connected to me?', '''What is one thing we can do to create more of those moments?''', '''open-ended''', '''Established''', '''medium'''),
('What is one need you want us to prioritize right now?', '''If we improved it, what would change day-to-day?''', '''open-ended''', '''Established''', '''medium'''),
('How do you want us to handle conflict when it shows up?', '''What helps you feel heard?''', '''open-ended''', '''Established''', '''medium'''),
('What is one boundary that would make our relationship healthier?', '''How do we respect it without feeling distant?''', '''open-ended''', '''Established''', '''medium'''),
('What is one shared goal you want us to work toward this year?', '''What is the first milestone we should set?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does reassurance look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does quality time look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does support look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does space look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does affection look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does communication look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does trust look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does teamwork look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does patience look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when you are stressed?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when we are busy?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when we disagree?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when we feel distant?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when we are planning the future?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when something feels off?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What does respect look like from me when we are making a big decision?', '''What is one example of it done well?''', '''open-ended''', '''Established''', '''medium'''),
('What is one assumption we sometimes make about each other? (1)', '''What would help us replace assumptions with clarity?''', '''open-ended''', '''Established''', '''medium'''),
('What is one assumption we sometimes make about each other? (2)', '''What would help us replace assumptions with clarity?''', '''open-ended''', '''Established''', '''medium'''),
('What is one assumption we sometimes make about each other? (3)', '''What would help us replace assumptions with clarity?''', '''open-ended''', '''Established''', '''medium'''),
('What is one assumption we sometimes make about each other? (4)', '''What would help us replace assumptions with clarity?''', '''open-ended''', '''Established''', '''medium'''),
('What is one assumption we sometimes make about each other? (5)', '''What would help us replace assumptions with clarity?''', '''open-ended''', '''Established''', '''medium'''),
('What do you need from me to feel fully supported?', '''What would support look like on a difficult day?''', '''open-ended''', '''Established''', '''deep'''),
('How has your understanding of love changed through us?', '''What moment taught you the most?''', '''open-ended''', '''Established''', '''deep'''),
('What would you like us to heal together?', '''What is the first honest conversation we should have?''', '''open-ended''', '''Established''', '''deep'''),
('If we had a relationship mission statement, what would it say?', '''What are the top 3 values in it?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (1)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (2)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (3)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (4)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (5)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (6)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (7)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (8)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (9)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (10)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (11)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (12)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (13)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (14)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (15)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (16)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (17)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (18)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (19)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (20)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (21)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (22)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (23)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (24)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (25)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (26)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (27)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (28)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (29)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (30)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (31)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (32)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (33)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (34)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (35)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep'''),
('What would make our relationship feel truly secure long-term? (36)', '''What does security look like for you?''', '''open-ended''', '''Established''', '''deep''');

-- MULTIPLE-CHOICE (100)
INSERT INTO questions (question_text, answer_text, question_type, context, difficulty, options) VALUES
('Which superpower would you pick for a day?', '''Which one fits your personality best?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "Flight"}, {"id": "b", "text": "Invisibility"}, {"id": "c", "text": "Time travel"}, {"id": "d", "text": "Mind reading"}]}'::jsonb),
('Your ideal weekend plan is:', '''What are you trying to get more of right now?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "Rest at home"}, {"id": "b", "text": "Social plans"}, {"id": "c", "text": "Outdoor adventure"}, {"id": "d", "text": "Productive catch-up"}]}'::jsonb),
('Pick your comfort vibe:', '''When do you usually crave this vibe?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "Cozy and quiet"}, {"id": "b", "text": "Bright and energetic"}, {"id": "c", "text": "Spontaneous and playful"}, {"id": "d", "text": "Simple and minimalist"}]}'::jsonb),
('Which setting helps you relax fastest?', '''What is one detail that makes it work?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "Beach"}, {"id": "b", "text": "Mountains"}, {"id": "c", "text": "City"}, {"id": "d", "text": "Countryside"}]}'::jsonb),
('Your go-to snack style is:', '''What does that say about your taste?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "Sweet"}, {"id": "b", "text": "Savory"}, {"id": "c", "text": "Spicy"}, {"id": "d", "text": "A mix of everything"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [8]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [9]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [10]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [11]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [12]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [13]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [14]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [15]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('When you are stressed, what helps most?', '''What is your healthiest go-to?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "Silence/alone time"}, {"id": "b", "text": "Talking to someone"}, {"id": "c", "text": "Exercise/movement"}, {"id": "d", "text": "Distraction/entertainment"}]}'::jsonb),
('How do you make big decisions?', '''What is one downside of your approach?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "Logic and analysis"}, {"id": "b", "text": "Gut feeling"}, {"id": "c", "text": "Ask trusted people"}, {"id": "d", "text": "List pros and cons"}]}'::jsonb),
('Which value matters most to you right now?', '''How do you live that value day-to-day?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "Stability"}, {"id": "b", "text": "Freedom"}, {"id": "c", "text": "Growth"}, {"id": "d", "text": "Connection"}]}'::jsonb),
('What is your learning style?', '''What is one subject you learned the hard way?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "Hands-on"}, {"id": "b", "text": "Reading"}, {"id": "c", "text": "Watching"}, {"id": "d", "text": "Coaching/mentorship"}]}'::jsonb),
('How do you recharge best?', '''What is one habit that blocks your recharge?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "Nature"}, {"id": "b", "text": "Friends"}, {"id": "c", "text": "Creative time"}, {"id": "d", "text": "Sleep"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [8]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [9]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [10]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [11]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [12]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [13]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [14]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [15]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [16]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [17]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [18]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [19]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [20]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [21]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [22]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [23]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [24]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [25]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which principle do you want to live by more consistently?', '''What would change if you did?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "Integrity"}, {"id": "b", "text": "Compassion"}, {"id": "c", "text": "Courage"}, {"id": "d", "text": "Discipline"}]}'::jsonb),
('Which fear shows up most often?', '''What is the smallest way to face it safely?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "Being alone"}, {"id": "b", "text": "Failing"}, {"id": "c", "text": "Not being enough"}, {"id": "d", "text": "Losing someone"}]}'::jsonb),
('What gives life meaning for you?', '''How do you protect that meaning?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "Faith/spirituality"}, {"id": "b", "text": "Relationships"}, {"id": "c", "text": "Service"}, {"id": "d", "text": "Creation"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Exploring''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('What kind of date night sounds best this week?', '''What would make it feel perfect?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "Cozy night in"}, {"id": "b", "text": "Nice dinner out"}, {"id": "c", "text": "Fun activity"}, {"id": "d", "text": "Walk and talk"}]}'::jsonb),
('What kind of support do you want today?', '''What should I avoid doing?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "Listen"}, {"id": "b", "text": "Help solve it"}, {"id": "c", "text": "Give space"}, {"id": "d", "text": "Do something practical"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [8]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''easy''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('When we disagree, what helps you most?', '''What would you like us to do differently?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "Talk immediately"}, {"id": "b", "text": "Take space then talk"}, {"id": "c", "text": "Write it out first"}, {"id": "d", "text": "Set a time to revisit"}]}'::jsonb),
('What is our biggest growth opportunity right now?', '''What would progress look like in 30 days?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "Communication"}, {"id": "b", "text": "Time together"}, {"id": "c", "text": "Shared goals"}, {"id": "d", "text": "Conflict skills"}]}'::jsonb),
('What do you need more of from me this month?', '''How will I know I am doing it well?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "Affection"}, {"id": "b", "text": "Attention"}, {"id": "c", "text": "Support"}, {"id": "d", "text": "Respect/space"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [8]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [9]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [10]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [11]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [12]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [13]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [14]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [15]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [16]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [17]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''medium''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('What should we protect at all costs in our relationship?', '''How do we protect it in a busy week?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "Respect"}, {"id": "b", "text": "Honesty"}, {"id": "c", "text": "Time"}, {"id": "d", "text": "Emotional safety"}]}'::jsonb),
('Which shared value matters most for our long-term future?', '''Where do we need to align more?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "Faith/meaning"}, {"id": "b", "text": "Family"}, {"id": "c", "text": "Growth"}, {"id": "d", "text": "Integrity"}]}'::jsonb),
('Which option fits you best right now? [1]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [2]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [3]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [4]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [5]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [6]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [7]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb),
('Which option fits you best right now? [8]', '''Why did you pick that one?''', '''multiple-choice''', '''Established''', '''deep''', '{"options": [{"id": "a", "text": "A"}, {"id": "b", "text": "B"}, {"id": "c", "text": "C"}, {"id": "d", "text": "D"}]}'::jsonb);
